### ISSUE TITLE
Proper behavior for games with the same name or moving directory

### ISSUE THREAD

**Issue by xythh** [KamWithK/exSTATic#16] opened 2023-01-09 02:00 UTC
I was counting the amount of hours I had read a visual novel and realized that the count was off.
I then did some digging and found a odd behavior.
I had moved the directory in which I had a game installed and exStatic failed to add the hours spent on the game before the game was moved.

ae8a2bbe-4c41-4298-8336-d272d2fa060c,Monkeys!!,Games/Monkeys!!/Monkeys!!.exe,vn,2023-01-05,37156,3443,10870.281999111176,3.4181265953393036

15ef8184-c2e3-423d-a595-085494d9d37e,Monkeys!!,Games/Monkeys/Monkeys!!.exe,vn,2023-01-06,31550,2895,7333.98899936676,4.301888099740009

Changing it to the follow in the exported csv and importing it fixed it.

ae8a2bbe-4c41-4298-8336-d272d2fa060c,Monkeys!!,Games/Monkeys/Monkeys!!.exe,vn,2023-01-05,37156,3443,10870.281999111176,3.4181265953393036

15ef8184-c2e3-423d-a595-085494d9d37e,Monkeys!!,Games/Monkeys/Monkeys!!.exe,vn,2023-01-06,31550,2895,7333.98899936676,4.301888099740009

This miscount was fixed by changed  the first line's given identifer to match the given identifer of the second.
If this is expected behavior, the stats window should show Two different Monkeys!! . Currently it combines them visual but the actual data is not combined.
If this is not expected behavior, then the stats should be merged or directory names should not be used for the given identifier

**Comment by KamWithK** [comment] 2023-02-01 00:59
I think this is the intended behavior. It's a feature not a bug! 🙂
The uuid is what actually distinguishes media entries, but you might want to have multiple different media which have separate uuid's but are displayed together. An example off this is if you were reading a series which had a VN and had a few LNs and a dozen manga volumes, you might want the VN, LNs and manga to all have separate uuid's (this is what naturally happens) but still be displayed together. To have this happen they all just need to have the exact same given name.

If I'm misunderstanding you then please let me know aha 😅

**Comment by xythh** [comment] 2023-02-01 02:18
Hi, firstly thank you for taking your time to reply, and trying to understand the mess that was my previous comment. :sweat_smile:

I see that combinding entries that have the same name makes a lot of sense, I did not consider that use case, so thank you for clearing that up.

The behavior that I do think is unexpected is that,I had two entries that shared the same uuid but the character counts and other information was not combined, although they were combined in the UI(Only one showed up and all previous datapoints on the graph were of the same color).

This behavior lead to the character count,play time and read speed all being incorrectly calculated.

I hope that was easier to understand than my previous comment, and thank you.

**Comment by KamWithK** [comment] 2023-02-01 22:01
So if it's correct on the UI where is it incorrect?

**Comment by xythh** [comment] 2023-02-01 22:55
It was not correct in the UI, the numbers were not accurate.

**Comment by xythh** [comment] 2023-02-02 17:41
![image](https://user-images.githubusercontent.com/121327029/216400731-48bb39a7-7f36-490a-a356-b7a50fdcfd47.png)
This was not correct.

**Comment by KamWithK** [comment] 2023-02-03 01:45
Sorry can you clarify exactly where on the stats page (or otherwise) it shows up correctly and incorrectly?
I can't tell from that little snapshot

**Comment by xythh** [comment] 2023-02-03 04:04
![image](https://user-images.githubusercontent.com/121327029/216509742-d6991e1e-0a37-43eb-b5cf-b7687cc151c8.png)
It was wrong there, it only gave the proper stats after I changed the directory of the first entry to match the second entry with the name Monkeys!!

**Comment by KamWithK** [comment] 2024-03-03 03:37
Low priority as this doesn't affect many people, closing for now

**Closed by KamWithK** 2024-03-03 03:37 UTC
